### ISSUE TITLE
I use  patch to Compile ti kernel4.4.32 ,boot ok lcd nodisplay

### ISSUE THREAD

**Issue by chenlinjiong** [bbvch/meta-ricoboard#1]
I use  patch to compile ti kernel4.4.32, patch is ok. compiled success.
boot matrix-rootfs ok. 
But lcd no dispaly
How can  i set ENV to display lcd

**Comment by messi1** [comment]
How did you connect your display? Is HDMI working?

**Comment by chenlinjiong** [comment]
I use myir original cable and lcd ,for kernel3.12.10 lcd display is ok

**Comment by chenlinjiong** [comment]
I have no hdmi cable ,so i can not test HDMI

**Comment by chenlinjiong** [comment]
Can you share the zImage and dtb file ,I can test it.Maybe I made a mistake.

**Comment by marcelbenz** [comment]
which LCD display do you use? Please check the dts file:
meta-ricoboard/recipes-kernel/linux/linux-ti-staging-4.4/0001-add-am437x-myir-ricoboard-dts.patch
maybe you have to adjust the display0 aliases

**Comment by chenlinjiong** [comment]
I'll try it

**Comment by chenlinjiong** [comment]
no help
next is loglist
U-Boot 2013.10-svn19 (Feb 05 2015 - 16:53:54)

I2C:   ready
DRAM:  512 MiB
lcd_bl_init
MMC:   OMAP SD/MMC: 0, OMAP SD/MMC: 1
SF: Detected S25FL128S_64K with page size 256 Bytes, erase size 64 KiB, total 16 MiB, mapped at 30000000
Init vbus0: 500mA@5V, OFF
Init vbus1: 500mA@5V, ON
Net:   <ethaddr> not set. Validating first E-fuse MAC
cpsw
Hit any key to stop autoboot:  0 
mmc1(part 0) is current device
reading /zImage
4461384 bytes read in 235 ms (18.1 MiB/s)
reading /myir_ricoboard.dtb
52263 bytes read in 7 ms (7.1 MiB/s)
Kernel image @ 0x80200000 [ 0x000000 - 0x441348 ]
## Flattened Device Tree blob at 80f80000
   Booting using the fdt blob at 0x80f80000
   Loading Device Tree to 9fb1d000, end 9fb2cc26 ... OK

Starting kernel ...

Booting Linux on physical CPU 0x0
Linux version 4.4.41-gf9f6f0db2d (am1@am1) (gcc version 4.7.3 20130226 (prerelease) (crosstool-NG linaro-1.13.1-4.7-2013.03-20130313 - Linaro GCC 2013.03) ) #1 Fri Jun 23 09:53:51 CST 2017
CPU: ARMv7 Processor [412fc09a] revision 10 (ARMv7), cr=10c53c7d
CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
Machine model: MYIR Rico Board
cma: Reserved 24 MiB at 0x9e000000
Memory policy: Data cache writeback
CPU: All CPU(s) started in SVC mode.
AM437x ES1.2 (sgx neon )
Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 130048
Kernel command line: console=ttyO0,115200n8 omapdss.def_disp=display0 omapfb.mode=display0:800x480MR-24@60 spi-ti-qspi.enable_qspi=1 root=/dev/mmcblk0p2 rw rootfstype=ext4
PID hash table entries: 2048 (order: 1, 8192 bytes)
Dentry cache hash table entries: 65536 (order: 6, 262144 bytes)
Inode-cache hash table entries: 32768 (order: 5, 131072 bytes)
Memory: 485628K/524288K available (6047K kernel code, 486K rwdata, 2116K rodata, 344K init, 240K bss, 14084K reserved, 24576K cma-reserved, 0K highmem)
Virtual kernel memory layout:
    vector  : 0xffff0000 - 0xffff1000   (   4 kB)
    fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
    vmalloc : 0xe0800000 - 0xff800000   ( 496 MB)
    lowmem  : 0xc0000000 - 0xe0000000   ( 512 MB)
    pkmap   : 0xbfe00000 - 0xc0000000   (   2 MB)
    modules : 0xbf000000 - 0xbfe00000   (  14 MB)
      .text : 0xc0008000 - 0xc0801054   (8165 kB)
      .init : 0xc0802000 - 0xc0858000   ( 344 kB)
      .data : 0xc0858000 - 0xc08d1970   ( 487 kB)
       .bss : 0xc08d3000 - 0xc090f330   ( 241 kB)
NR_IRQS:16 nr_irqs:16 16
L2C: platform modifies aux control register: 0x0e030000 -> 0x3e430000
L2C: DT/platform modifies aux control register: 0x0e030000 -> 0x3e430000
L2C-310 enabling early BRESP for Cortex-A9
OMAP L2C310: ROM does not support power control setting
L2C-310 dynamic clock gating disabled, standby mode disabled
L2C-310 cache controller enabled, 16 ways, 256 kB
L2C-310: CACHE_ID 0x410000c9, AUX_CTRL 0x4e430000
OMAP clockevent source: timer2 at 24000000 Hz
sched_clock: 32 bits at 24MHz, resolution 41ns, wraps every 89478484971ns
clocksource: timer1: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 79635851949 ns
OMAP clocksource: timer1 at 24000000 Hz
clocksource: 32k_counter: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 58327039986419 ns
OMAP clocksource: 32k_counter at 32768 Hz
Console: colour dummy device 80x30
Calibrating delay loop... 1196.85 BogoMIPS (lpj=5984256)
pid_max: default: 32768 minimum: 301
Security Framework initialized
Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
CPU: Testing write buffer coherency: ok
Setting up static identity map for 0x800082c0 - 0x80008338
devtmpfs: initialized
VFP support v0.3: implementor 41 architecture 3 part 30 variant 9 rev 4
clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
pinctrl core: initialized pinctrl subsystem
NET: Registered protocol family 16
DMA: preallocated 256 KiB pool for atomic coherent allocations
cpuidle: using governor ladder
cpuidle: using governor menu
omap_gpio 44e07000.gpio: could not find pctldev for node /ocp/l4_wkup@44c00000/scm@210000/pinmux@800/gpio0_pins, deferring probe
OMAP GPIO hardware version 0.1
No ATAGs?
hw-breakpoint: found 5 (+1 reserved) breakpoint and 1 watchpoint registers.
hw-breakpoint: maximum watchpoint size is 4 bytes.
omap4_sram_init:Unable to get sram pool needed to handle errata I688
edma 49000000.edma: TI EDMA DMA engine driver
vgaarb: loaded
SCSI subsystem initialized
usbcore: registered new interface driver usbfs
usbcore: registered new interface driver hub
usbcore: registered new device driver usb
omap_i2c 44e0b000.i2c: could not find pctldev for node /ocp/l4_wkup@44c00000/scm@210000/pinmux@800/i2c0_pins, deferring probe
omap_i2c 4802a000.i2c: could not find pctldev for node /ocp/l4_wkup@44c00000/scm@210000/pinmux@800/i2c1_pins_default, deferring probe
media: Linux media interface: v0.10
Linux video capture interface: v2.00
pps_core: LinuxPPS API ver. 1 registered
pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
PTP clock support registered
omap-mailbox 480c8000.mailbox: omap mailbox rev 0x400
clocksource: Switched to clocksource timer1
NET: Registered protocol family 2
TCP established hash table entries: 4096 (order: 2, 16384 bytes)
TCP bind hash table entries: 4096 (order: 2, 16384 bytes)
TCP: Hash tables configured (established 4096 bind 4096)
UDP hash table entries: 256 (order: 0, 4096 bytes)
UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
NET: Registered protocol family 1
RPC: Registered named UNIX socket transport module.
RPC: Registered udp transport module.
RPC: Registered tcp transport module.
RPC: Registered tcp NFSv4.1 backchannel transport module.
NetWinder Floating Point Emulator V0.97 (double precision)
futex hash table entries: 256 (order: -1, 3072 bytes)
VFS: Disk quotas dquot_6.6.0
VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
NFS: Registering the id_resolver key type
Key type id_resolver registered
Key type id_legacy registered
jffs2: version 2.2. (NAND) (SUMMARY)  © 2001-2006 Red Hat, Inc.
NET: Registered protocol family 38
io scheduler noop registered
io scheduler deadline registered
io scheduler cfq registered (default)
pinctrl-single 44e10800.pinmux: 199 pins at pa f9e10800 size 796
backlight supply power not found, using dummy regulator
4832a000.dss supply vdda_video not found, using dummy regulator
OMAP DSS rev 2.0
omapdss_dss 4832a000.dss: bound 4832a400.dispc (ops dispc_component_ops)
omapfb omapfb: no displays
omapfb omapfb: failed to setup omapfb
Serial: 8250/16550 driver, 4 ports, IRQ sharing enabled
omap_uart 44e09000.serial: no wakeirq for uart0
omap_uart 44e09000.serial: No clock speed specified: using default: 48000000
44e09000.serial: ttyO0 at MMIO 0x44e09000 (irq = 30, base_baud = 3000000) is a OMAP UART0
console [ttyO0] enabled
omap_rng 48310000.rng: OMAP Random Number Generator ver. 20
brd: module loaded
loop: module loaded
mtdoops: mtd device (mtddev=name/number) must be supplied
davinci_mdio 4a101000.mdio: davinci mdio revision 1.6
davinci_mdio 4a101000.mdio: detected phy mask fffffffe
libphy: 4a101000.mdio: probed
davinci_mdio 4a101000.mdio: phy[0]: device 4a101000.mdio:00, driver unknown
cpsw 4a100000.ethernet: Detected MACID = 68:9e:19:b8:40:8d
cpsw 4a100000.ethernet: cpts: overflow check period 850
usbcore: registered new interface driver asix
usbcore: registered new interface driver ax88179_178a
usbcore: registered new interface driver cdc_ether
usbcore: registered new interface driver smsc95xx
usbcore: registered new interface driver net1080
usbcore: registered new interface driver cdc_subset
usbcore: registered new interface driver zaurus
usbcore: registered new interface driver cdc_ncm
dwc3 48390000.usb: CONFIG_USB_OTG needed for dual-role
dwc3 48390000.usb: limiting to peripheral only
ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
ehci-pci: EHCI PCI platform driver
ehci-omap: OMAP-EHCI Host Controller driver
xhci-hcd xhci-hcd.0.auto: xHCI Host Controller
xhci-hcd xhci-hcd.0.auto: new USB bus registered, assigned bus number 1
xhci-hcd xhci-hcd.0.auto: hcc params 0x0238f06d hci version 0x100 quirks 0x00210010
xhci-hcd xhci-hcd.0.auto: irq 256, io mem 0x483d0000
usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
usb usb1: Product: xHCI Host Controller
usb usb1: Manufacturer: Linux 4.4.41-gf9f6f0db2d xhci-hcd
usb usb1: SerialNumber: xhci-hcd.0.auto
hub 1-0:1.0: USB hub found
hub 1-0:1.0: 1 port detected
xhci-hcd xhci-hcd.0.auto: xHCI Host Controller
xhci-hcd xhci-hcd.0.auto: new USB bus registered, assigned bus number 2
usb usb2: We don't know the algorithms for LPM for this host, disabling LPM.
usb usb2: New USB device found, idVendor=1d6b, idProduct=0003
usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
usb usb2: Product: xHCI Host Controller
usb usb2: Manufacturer: Linux 4.4.41-gf9f6f0db2d xhci-hcd
usb usb2: SerialNumber: xhci-hcd.0.auto
hub 2-0:1.0: USB hub found
hub 2-0:1.0: 1 port detected
usbcore: registered new interface driver cdc_wdm
usbcore: registered new interface driver usb-storage
mousedev: PS/2 mouse device common for all mice
omap_rtc 44e3e000.rtc: already running
omap_rtc 44e3e000.rtc: rtc core: registered 44e3e000.rtc as rtc0
i2c /dev entries driver
Driver for 1-wire Dallas network protocol.
omap_wdt: OMAP Watchdog Timer Rev 0x01: initial timeout 60 sec
ledtrig-cpu: registered to indicate activity on CPUs
omap-aes 53501000.aes: OMAP AES hw accel rev: 0.1
omap-des 53701000.des: OMAP DES hw accel rev: 0.33
omap-sham 53100000.sham: hw accel on OMAP rev 0.0
usbcore: registered new interface driver usbhid
usbhid: USB HID core driver
oprofile: no performance counters
oprofile: using timer interrupt.
Initializing XFRM netlink socket
NET: Registered protocol family 17
NET: Registered protocol family 15
8021q: 802.1Q VLAN Support v1.8
Key type dns_resolver registered
omap_voltage_late_init: Voltage driver support not added
ThumbEE CPU extension supported.
mmc0: MAN_BKOPS_EN bit is not set
GPIO line 183 (SelEMMCorNAND) hogged as output/low
mmc0: new high speed MMC card at address 0001
mmcblk0: mmc0:0001 P1XXXX 3.60 GiB 
mmcblk0boot0: mmc0:0001 P1XXXX partition 1 2.00 MiB
mmcblk0boot1: mmc0:0001 P1XXXX partition 2 2.00 MiB
 mmcblk0: p1 p2 p3
ov2659 0-0030: link-frequencies property not found or too many
ov2659 0-0030: platform data not specified
ov2659: probe of 0-0030 failed with error -22
omap_i2c 44e0b000.i2c: bus 0 rev0.12 at 100 kHz
ov2659 1-0030: link-frequencies property not found or too many
ov2659 1-0030: platform data not specified
ov2659: probe of 1-0030 failed with error -22
omap_i2c 4802a000.i2c: bus 1 rev0.12 at 100 kHz
omapfb omapfb: no displays
omapfb omapfb: failed to setup omapfb
omap_hsmmc 48060000.mmc: Got CD GPIO
omapfb omapfb: no displays
omapfb omapfb: failed to setup omapfb
input: gpio_keys as /devices/platform/gpio_keys/input/input0
omapfb omapfb: no displays
omapfb omapfb: failed to setup omapfb
omap_rtc 44e3e000.rtc: setting system clock to 2014-06-09 20:19:11 UTC (1402345151)
vdd_vbus1: disabling
EXT4-fs (mmcblk0p2): recovery complete
EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
VFS: Mounted root (ext4 filesystem) on device 179:2.
devtmpfs: mounted
Freeing unused kernel memory: 344K (c0802000 - c0858000)
This architecture does not have kernel memory protection.
INIT: version 2.88 booting
Error opening /dev/fb0: No such file or directory
Starting udev
udevd[901]: starting version 182
FAT-fs (mmcblk0p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
FAT-fs (mmcblk0p3): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
ERROR: could not open directory /lib/modules/4.4.41-gf9f6f0db2d: No such file or directory
WARNING: -e needs -E or -F
ERROR: could not open directory /lib/modules/4.4.41-gf9f6f0db2d: No such file or directory
FATAL: could not search modules: No such file or directory
Starting Bootlog daemon: bootlogd: cannot allocate pseudo tty: No such file or directory
bootlogd.
EXT4-fs (mmcblk0p2): re-mounted. Opts: data=ordered
random: dd: uninitialized urandom read (512 bytes read, 52 bits of entropy available)
ALSA: Restoring mixer settings...
/usr/sbin/alsactl: load_state:1696: No soundcards found...
Configuring network interfaces... net eth0: initializing cpsw version 1.15 (0)
net eth0: initialized cpsw ale version 1.4
net eth0: ALE Table size 1024
omapfb omapfb: no displays
omapfb omapfb: failed to setup omapfb
net eth0: phy found : id is : 0x221622
8021q: adding VLAN 0 to HW filter on device eth0
udhcpc (v1.20.2) started
Sending discover...
Sending discover...
Sending discover...
No lease, failing
done.
INIT: Entering runlevel: 5
Starting system message bus: random: dbus-daemon: uninitialized urandom read (12 bytes read, 60 bits of entropy available)
random: dbus-daemon: uninitialized urandom read (12 bytes read, 61 bits of entropy available)
dbus.
UIM SYSFS Node Not Found
Starting Dropbear SSH server: random: dropbear: uninitialized urandom read (32 bytes read, 62 bits of entropy available)
dropbear.
Starting telnet daemon.
Starting syslogd/klogd: done
Starting thttpd.
Starting Lighttpd Web Server: random: lighttpd: uninitialized urandom read (4096 bytes read, 63 bits of entropy available)
lighttpd.
2014-06-09 20:19:26: (log.c.166) server started 
/
Starting Matrix GUI application.
/etc/rc5.d/S98set-max-speed: line 8: /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor: No such file or directory
cat: can't open '/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies': No such file or directory
grep: invalid option -- '1'
cat: can't open '/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies': No such file or directory
BusyBox v1.20.2 (2014-06-09 09:47:39 CDT) multi-call binary.

Usage: grep [-HhnlLoqvsriwFE] [-m N] [-A/B/C N] PATTERN/-e PATTERN.../-f FILE [FILE]...

random: nonblocking pool is initialized
***************************************************************
***************************************************************
NOTICE: This file system contains the followin GPLv3 packages:
        binutils-symlinks
        binutils
        gdbserver

If you do not wish to distribute GPLv3 components please remove
the above packages prior to distribution.  This can be done using
the opkg remove command.  i.e.:
    opkg remove <package>
Where <package> is the name printed in the list above

NOTE: If the package is a dependency of another package you
      will be notified of the dependent packages.  You should
      use the --force-removal-of-dependent-packages option to
      also remove the dependent packages as well
***************************************************************
***************************************************************
Start led_play daemon.
1386
Stopping Bootlog daemon: bootlogd.

 _____                    _____           _         _   
|  _  |___ ___ ___ ___   |  _  |___ ___  |_|___ ___| |_ 
|     |  _| .'| . | . |  |   __|  _| . | | | -_|  _|  _|
|__|__|_| |__,|_  |___|  |__|  |_| |___|_| |___|___|_|  
              |___|                    |___|            

Arago Project http://arago-project.org m437x-evm ttyO0

Arago 2013.12 m437x-evm ttyO0

m437x-evm login:

**Comment by messi1** [comment]
It seems your config is wrong:
omapfb omapfb: no displays
omapfb omapfb: failed to setup omapfb
omap_hsmmc 48060000.mmc: Got CD GPIO
omapfb omapfb: no displays
omapfb omapfb: failed to setup omapfb

Check your config or contact Myir.
